name: Query Titans Book (Python Only)

on:
  workflow_dispatch:

jobs:
  query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install python-chess

      - name: Query book using Python
        run: python3 query_book.py
