name: Extract PGN from OPTIMUS2502.bin

on:
  workflow_dispatch:

jobs:
  extract-pgn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install python-chess polyglot six 

      - name: Extract PGN from .bin
        run: |
          python extract_pgn_from_bin.py

      - name: Upload PGN artifact
        uses: actions/upload-artifact@v4
        with:
          name: Optical.pgn
          path: engines/Optical.pgn
