name: Build Polyglot Book

on:
  workflow_dispatch:
  push:
    paths:
      - 'book/custom_book.pgn'
      - '.github/workflows/make-book.yml'

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install polyglot
        run: |
          sudo apt update
          sudo apt install -y polyglot

      - name: Create PGN file
        run: |
          mkdir -p book
          echo "[Event \"Custom Opening\"]" > book/custom_book.pgn
          echo "[Site \"?\"]" >> book/custom_book.pgn
          echo "[Date \"2025.06.29\"]" >> book/custom_book.pgn
          echo "[Round \"-\"]" >> book/custom_book.pgn
          echo "[White \"?\"]" >> book/custom_book.pgn
          echo "[Black \"?\"]" >> book/custom_book.pgn
          echo "[Result \"*\"]" >> book/custom_book.pgn
          echo "" >> book/custom_book.pgn
          echo "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 O-O 8. c3 d6 9. h3 Na5 10. Bc2 c5 *" >> book/custom_book.pgn

      - name: Generate Polyglot .bin book
        run: |
          polyglot make-book -pgn book/custom_book.pgn -bin book/book.bin -min-game 1 -max-ply 40

      - name: Upload .bin as GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: opening-book
          path: book/book.bin
